Step 1: Import Libraries

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier

%matplotlib inline

Step 2: Load Dataset

In [2]:
df = pd.read_csv("../data/processed/creditcard_clean.csv")

Step 3: Display Dataset

In [3]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

Step 4: Separate Features and Target

In [4]:
X = df.drop("Class", axis=1)

y = df["Class"]

Step 5: Verify Features

In [5]:
print(X.columns)

Index(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount'],
      dtype='str')

Step 6: Train-Test Split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

Step 7: Feature Scaling

In [7]:
scaler = StandardScaler()

X_train[["Time","Amount"]] = scaler.fit_transform(
    X_train[["Time","Amount"]]
)

X_test[["Time","Amount"]] = scaler.transform(
    X_test[["Time","Amount"]]
)

Step 8: Verify Scaling

In [8]:
X_train[["Time","Amount"]].describe()

               Time        Amount
count  2.269800e+05  2.269800e+05
mean  -1.522636e-16  7.487965e-17
std    1.000002e+00  1.000002e+00
min   -1.998400e+00 -3.596386e-01
25%   -8.561822e-01 -3.364866e-01
50%   -2.123526e-01 -2.697972e-01
75%    9.363191e-01 -4.287453e-02
max    1.640237e+00  7.962087e+01

Step 9: check number of features

In [10]:
print("Number of Features:", X_train.shape[1])

print("\nFeature Names:\n")

print(X_train.columns.tolist())

Number of Features: 30

Feature Names:

['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount']

Step 10: Identify Features That Need Scaling

In [11]:
X_train[["Time", "Amount"]].describe()

               Time        Amount
count  2.269800e+05  2.269800e+05
mean  -1.522636e-16  7.487965e-17
std    1.000002e+00  1.000002e+00
min   -1.998400e+00 -3.596386e-01
25%   -8.561822e-01 -3.364866e-01
50%   -2.123526e-01 -2.697972e-01
75%    9.363191e-01 -4.287453e-02
max    1.640237e+00  7.962087e+01

Step 11: Check for Constant Columns

In [12]:
constant_columns = []

for col in X_train.columns:
    if X_train[col].nunique() == 1:
        constant_columns.append(col)

print("Constant Columns:")
print(constant_columns)

Constant Columns:
[]

Step 12: Verify Final Feature Matrix

In [13]:
print("Training Features :", X_train.shape)
print("Testing Features  :", X_test.shape)

print("Training Labels   :", y_train.shape)
print("Testing Labels    :", y_test.shape)

Training Features : (226980, 30)
Testing Features  : (56746, 30)
Training Labels   : (226980,)
Testing Labels    : (56746,)

Step 13: Save the Engineered Dataset

In [14]:
X_train.to_csv(
    "../data/processed/X_train_engineered.csv",
    index=False
)

X_test.to_csv(
    "../data/processed/X_test_engineered.csv",
    index=False
)

y_train.to_csv(
    "../data/processed/y_train.csv",
    index=False
)

y_test.to_csv(
    "../data/processed/y_test.csv",
    index=False
)

Step 14: Verify Saved Files

In [15]:
import os

print(os.listdir("../data/processed"))

['creditcard_backup.csv', 'creditcard_clean.csv', 'X_scaled.csv', 'X_test_engineered.csv', 'X_train_engineered.csv', 'X_train_smote.csv', 'y.csv', 'y_test.csv', 'y_train.csv', 'y_train_smote.csv']